name: remote-push
on:
  push:
    branches:
      - main
env:
  SRC: ${{github.workspace}}
  VAULT_ROOT_TOKEN: ${{ secrets.VAULT_ROOT_TOKEN }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR}}
  GCP_PROJECT_NAME: "${{ secrets.GCP_PROJECT_NAME }}"
  GCP_SERVICE_ACCOUNT_ADMIN : "${{ secrets.GCP_SERVICE_ACCOUNT_ADMIN }}"
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"
  TERRAFORM_BUCKET_NAME": "${{ secrets.TERRAFORM_BUCKET_NAME }}"
  GOOGLE_APPLICATION_CREDENTIALS: "/tmp/gsa_key.json"
  BUILDX_NO_DEFAULT_ATTESTATIONS: "1"
jobs:
  remote-push:
    runs-on: ubuntu-latest
    steps:
      - name: run git safe.directory
        if: ${{ github.event.inputs.LOCAL == 'true' }}
        run: git config --global --add safe.directory "*"
      - name: "check github repository"
        uses: actions/checkout@v3
      - name: Run Instructions Action
        id: detect-files
        uses: ghostmind-dev/detect@main
        with:
          commit-message: ${{ github.event.head_commit.message }}
          possible-instructions: "web,state,all"
          instructions-keyword: "INSTRUCTIONS="
    outputs:
      result: ${{ steps.detect-files.outputs.result }}
  remote-state:
    runs-on: ubuntu-latest
    needs: remote-push
    if: |-
      ${{ 
        needs.remote-push.outputs.result == 'state' || 
        needs.remote-push.outputs.result == 'all'  ||
        github.event.inputs.LOCAL == 'true'
      }}
    steps:
      - name: run git safe.directory
        if: ${{ github.event.inputs.LOCAL == 'true' }}
        run: git config --global --add safe.directory "*"
      - name: "check github repository"
        uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Node.js script
        uses: ghostmind-dev/action@main
     
 